### ISSUE TITLE
Too many strings in API V2 responses

### ISSUE THREAD

**Issue by ryanpetrie-thevoid** [innius/grafana-simple-grpc-datasource#4]
Hello, love the library so far!

Looking over the V2 API, I noticed that it's sending a lot of strings per response, and I'm concerned about efficiency and bandwidth. 

For each Frame, the response includes the metric name and a collection of Fields. Each field also includes the name (I assume the metric name), and associated labels, config (which is unit of measure - also a string), and the value. That means that *per data value* I'm sending any number of strings (a name, a config, and an unbounded number of label keys and values).

Off the cuff, may I suggest something like:

```
message GetMetricValueResponse {
  repeated SingleValueField fields = 1;
}

message GetMetricHistoryResponse {
  repeated Field fields = 1;
}

message Sample {
  google.protobuf.Timestamp timestamp = 1;
  double value = 2;
}

message Field {
  string metric = 1;
  repeated Label labels = 2;
  repeated Sample data = 3;
}

// Or just reuse Field, with a single entry in 'data'
message SingleValueField {
  string metric = 1;
  repeated Label labels = 2;
  Sample data = 3;
}
```

I'd also suggest moving `config` entirely into the metric definition; that is, part of the `ListMetricsResponse.Metric` message.

**Comment by rvdwijngaard** [comment]
Hello, thanks for creating this issue. 

The idea behind this V2 API was to align more with [grafana data frame API](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/dataFrame.ts). According to their API definition one `Frame` can have multiple `Fields`. You will find the same pattern in the V2 API.  I am not sure if I agree with you that all these strings are sent for each *data value*. Each field has two arrays with timestamps and double values. 

If I would follow your proposal I'd loose this Frame level which means this plugin cannot return multiple frames with one response. I believe there are two different scenarios: 
1. there are multiple measures with the same timestamp -> one frame with multiple fields (eg. temperature, pressure etc)
2. there are multiple measures with different timestamps -> each  measure is a frame with only one value. 

I believe your proposal only support the second scenario. 

Scenario 1: Current V2 API
timestamp: 12:01:00, temperature 21.1℃ , pressure 1030 hpa
timestamp: 13:10.10, temperature 21.9℃ , pressure 1031 hpa

```json
{
  "frames" : [
    {
      "metric" :  "room1", 
      "timestamps": [ "12:01:00", "13:10:10"],
      "fields": [ 
         {
           "name" : "temperature",
           "labels" : [],
           "values" : [ 21.1, 21.9]
         },
        {
           "name" : "pressure",
           "labels" : [],
           "values" : [1030, 1039]
         }
       ] 
    }
  ]
}
```
With your proposal this would become: 

```json
{
  "fields": [
    {
      "metric": "temperature",
      "labels": [],
      "data": [
        {
          "timestamp": "12:01:00",
          "value": 21.1
        },
        {
          "timestamp": "13:10:00",
          "value": 21.9
        }
      ]
    },
    {
      "metric": "pressure",
      "labels": [],
      "data": [
        {
          "timestamp": "12:01:00",
          "value": 1030
        },
        {
          "timestamp": "13:10:00",
          "value": 1039
        }
      ]
    }
  ]
}
```
In scenario 2 we have two rooms with each their own measures: 
```json 
{
  "frames" : [
    {
      "metric" :  "room1", 
      "timestamps": [ "12:01:00", "13:10:10"],
      "fields": [ 
         {
           "name" : "temperature",
           "labels" : [],
           "values" : [ 21.1, 21.9]
         },
        {
           "name" : "pressure",
           "labels" : [],
           "values" : [1030, 1039]
         }
       ] 
    },
    {
      "metric" :  "room2", 
      "timestamps": [ "11:01:00", "12:10:10"],
      "fields": [ 
         {
           "name" : "temperature",
           "labels" : [],
           "values" : [ 22.1, 22.9]
         },
        {
           "name" : "pressure",
           "labels" : [],
           "values" : [1130, 1139]
         }
       ] 
    }
  ]
}
````

I don't see how this last scenario would fit in your proposal. Perhaps I am missing something here. 

It is also good to mention that the V2 API is optional. The old API is still supported. 

see #2  for some examples.

**Comment by bmo-at** [comment]
Also  if you are concerned about efficency @ryanpetrie-thevoid, may I point out that sending the strings is mostly optional?
The only required string, as best I can tell is the `metric` string. If you leave the name of the fields blank, the plugin will just substitue it with `"value"`, which for multiple fields grafana itself will rename with numbered names to tell them apart.
So really, you only have to send one string, and that one is pretty central to making the data readable.

**Comment by ryanpetrie-thevoid** [comment]
Thanks for the detailed response and explanation.
