### ISSUE TITLE
[Suggestion] Send back already selected dimension keys/values as part of a ListDimensionKeysRequest/ListDimensionValuesRequest 

### ISSUE THREAD

**Issue by bmo-at** [innius/grafana-simple-grpc-datasource#5]
Sometimes one might want to tailor the available dimensions or their values to what has already been selected.
For example, if the user has already selected a value for a dimension that the they should not be able to select twice, we might want to take that dimension out of the response for the next request. But currently, there is no way to know which dimensions the user has already selected.

**Comment by rvdwijngaard** [comment]
Thanks for your suggestion.

**Comment by bmo-at** [comment]
I took the liberty to implement this and contribute back under #6

**Comment by rvdwijngaard** [comment]
version v1.0.7 has been published
