### ISSUE TITLE
Filter for dimension values not refreshing for dashboard variable

### ISSUE THREAD

**Issue by jahaugum** [innius/grafana-simple-grpc-datasource#9]
Thanks for a great plugin, and I really like the new feature with dashboard variables for dimensions.

I use a dimension with a high number of values, and I return a limited number of values in ListDimensionValues. This works perfectly in the query editor where it calls ListDimensionValues on every filter change. But this is not the behavior in the dashboard variable for dimension, where is only calls ListDimensionValues initially on not on any filter change. Then the filter only works for the reduced values I returned in the first place.

Is it feasible to get this refreshed on every filter change?

**Comment by rvdwijngaard** [comment]
Hi @jahaugum not sure if this is possible. I'll have to investigate this in detail.

**Comment by rvdwijngaard** [comment]
just to confirm I understood the problem correctly. You want to configure a variable of type `DimensionValue`. After selecting the appropriate Dimension Key, a list of Dimension Values is returned by the backend system. In your case, a particular dimension, has many values and you only return a limited set. As a result you only see the limited number of dimensions and there is no way to get to the other dimension values. Is that correct?

**Comment by rvdwijngaard** [comment]
alright. I understand. I think the best solution would be to provide the VariableQueryEditor with a filter field which is send to the backend. This would provide the same behavior like the Query Editor. What do you think?

**Comment by jahaugum** [comment]
I'm very happy with how it works in the QueryEditor, so that sound like a good solution.
